### ISSUE TITLE
Licensing clarification

### ISSUE THREAD

**Issue by gouthamve** [embrace-io/embrace-android-sdk#808]
Thanks a lot for building and releasing this SDK! Excited to see more innovation in the mobile + OTel space!

I see that the license of this repo is AGPL. From what I understand both GPL and AGPL are viral licenses, and if I build an app with the embrace SDK, I am obligated to also license my app as AGPL, which seems too restrictive imo.

Could you provide clarity on this? Can I build and release an App with the embrace SDK without having to AGPL the source code of the App?

**Comment by andrewtunall** [comment]
Thanks for the feedback @gouthamve - we're excited too! We've been having discussions with customers and the community about this, as we were hoping to get feedback on the license, and will be updating the license to Apache 2.0.

**Comment by gouthamve** [comment]
Looks like its been updated to Apache 2.0! That is great to see!
